trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  appDir: ng-kitchen-app

steps:
- task: NodeTool@0
  displayName: node install
  inputs:
    versionSpec: '14.x'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDir)

- script: npx ng build --prod
  displayName: ng build
  workingDirectory: $(appDir)

- task: SonarCloudPrepare@1
  displayName: sonarcloud prepare
  inputs:
    SonarCloud: 'sonarcloud-escalonn'
    organization: '2011-nov02-net'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '2011-nov02-net_nick-project2-kitchen-site'
    cliProjectName: 'Nick Kitchen Site'
    cliProjectVersion: '1.0.0'
    cliSources: '$(appDir)/src,$(appDir)/e2e'
    extraProperties: 'sonar.coverage.exclusions=**/*.spec.ts,$(appDir)/e2e/**/*'

- task: SonarCloudAnalyze@1
  displayName: sonarcloud run

- task: SonarCloudPublish@1
  displayName: sonarcloud publish
  inputs:
    pollingTimeoutSec: '300'

- task: AzureRmWebAppDeployment@4
  displayName: azure app service deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(0518cd5b-d389-4983-9496-cdcae31dcc60)'
    appType: 'webApp'
    WebAppName: 'nick-project2-kitchen-site'
    packageForLinux: '$(appDir)/dist/$(appDir)'
